version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    
    steps:
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      
      - checkout
      - run: go test -v ./tests/...

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
